Update deploy.yaml

diff --git a/.github/workflows/deploy.yaml b/.github/workflows/deploy.yaml
--- a/.github/workflows/deploy.yaml
+++ b/.github/workflows/deploy.yaml
@@ -42,6 +42,10 @@ jobs:
           echo "commit_hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
           echo "timestamp=$(date +'%Y-%m-%d-%H-%M')" >> $GITHUB_ENV
 
+      # Debug Image Tag
+      - name: Debug Image Tag
+        run: echo "Image Tag: ${{ env.commit_hash }}-${{ env.timestamp }}"
+
       # Build Docker image
       - name: Build Docker Image
         id: build-image
@@ -76,7 +80,8 @@ jobs:
       - name: Snyk Scan Docker Image
         run: |
           echo "Running Snyk scan on Docker image..."
-          snyk test --docker $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --severity-threshold=low --json > snyk-result.json || true
+          docker images
+          snyk test --docker $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --severity-threshold=low --json > snyk-result.json || { echo "Snyk scan failed"; cat snyk-result.json; exit 1; }
           snyk monitor --docker $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG --severity-threshold=low
           cat snyk-result.json
         env:
